name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: echo "Build the project"
    - name: Store artifacts
      run: echo "Artifacts were stored",
  
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests on previously built binary
      run: echo "Run tests"


  release:
    runs-on: ubuntu-latest
    environment: Release
    steps:
    - uses: actions/checkout@v2
      run: echo "wait for approval" 
