name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the project
      run: echo "Build the project"
    - name: Store artifacts
      run: echo "Artifacts were stored",
  
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests on previously built binary
      run: echo "Run tests"

  pre-release:
    runs-on: ubuntu-latest
    environment: Release
    needs: [ build, tests ]
    steps:
    - uses: actions/checkout@v2
    - name: Wait for approval 
      run: echo "wait for approval" 

  release:
    runs-on: ubuntu-latest
    environment: Release
    needs: [ build, tests, pre-release ]
    steps:
    - uses: actions/checkout@v2
    - name: Wait for approval 
      run: echo "wait for approval" 
